Write a class that generates fake data.

* Write the code under the py docs ( do NOT remove py docs )
* Before comitting do a Restart & Run All

In [1]:

class FakeDataGenerator:
    
    def __init__(self, df = None, rows=5):
        """
        This class generates fake data
        
        If data frame is passed in it will add the fake data to it. 
        Otherwise, it will create a new data frame
        
        Parameters:
        -----------
        df: 
          DataFrame default is None
          
        rows:
          If df None, this parameter will be used to create a data frame with `row` lenght
        """
        # code goes under this line. 
        # I will deduct points if any code is written above the comments!
        
        if df is None:
            self.df = pd.DataFrame(index=range(rows))
        else:
            self.df = df
        
        
    def add_random_number(self, column_name, small_value, high_value): # optional: add probabilities 
        """
        adds fake numbers to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        
        self.df[column_name] = [randint(small_value,high_value) for i in range(self.df.shape[0])]
        return self.df
    
        
    def add_name(self, column_name):
        """
        adds fake name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        self.df[column_name] = [faker.name() for i in range(self.df.shape[0])]
        return self.df
    
    
    def add_last_name(self, column_name):
        """
        adds fake last name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        self.df[column_name] = [faker.last_name() for i in range(self.df.shape[0])]
        return self.df
    
    
    def add_email(self, column_name):
        """
        adds fake email to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        self.df[column_name] = [faker.email() for i in range(self.df.shape[0])]
        return self.df
    
    
    def add_phone_number(self, column_name):
        """
        adds fake name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        self.df[column_name] = [faker.phone_number() for i in range(self.df.shape[0])]
        return self.df
    
    
    def add_address(self, column_name):
        """
        adds fake name to the data frame with `column_name`
        
        Returns
        -------
        data frame
        """
        self.df[column_name] = [faker.address() for i in range(self.df.shape[0])]
        return self.df

In [2]:
import pandas as pd
from faker import Faker
from random import randint
faker = Faker()

# Case 1 - existing data frame 
df = pd.DataFrame()
df['product_id'] = [i + 123 for i in range(25)]
df.head()

   product_id
0         123
1         124
2         125
3         126
4         127

In [3]:
fakeGen = FakeDataGenerator(df) # I'm creating instance using existing df
fakeGen.add_address('shipping_address')
fakeGen.add_address('billing_address')
fakeGen.add_phone_number('customer_phone')

,product_id,shipping_address,billing_address,customer_phone
0,123,"262 Amanda Glens\nJessicamouth, FL 07953","23428 Lowe Valley\nLake Vincent, OK 82790",(080)573-6413
1,124,"89985 Sean Locks Suite 799\nMossview, AL 62435",335 Dickerson Shoals Suite 320\nNew Alexisside...,4774577794
2,125,"39958 Freeman Burg Apt. 398\nNew Ericton, MA 9...","9279 Fuller Shore Suite 358\nJoyceton, RI 55428",881.674.7575
3,126,"62906 Anna Circle\nLake Mauriceport, NE 43063","859 Pena Village\nWilsonton, AZ 15212",+1-142-034-5376
4,127,70338 Christian Passage Suite 083\nPort Marych...,"6010 Jane Prairie Suite 128\nLake Jose, VA 28521",001-625-357-1026
5,128,USNV Doyle\nFPO AA 38218,"428 Corey Highway Suite 957\nEast Jonathan, NM...",577.033.8599x387
6,129,"7068 Tanya Highway\nVincentville, CO 64233",Unit 5665 Box 9402\nDPO AE 26346,001-641-245-9573x869
7,130,"8530 Elizabeth Point\nTaylorshire, ND 70017","8312 William Pike Suite 729\nMichellebury, NY ...",694.041.2275
8,131,"0897 Andre Mount\nPort Sheila, LA 91579",USS Bell\nFPO AE 39343,001-721-842-4637x7141
9,132,"662 Baxter Cape\nKevinmouth, NE 00590","34439 Kim Corners\nWest Anthony, ID 24497",(625)325-8514
10,133,"1447 Ruiz Extensions\nNorth Lisa, WY 88184",613 Ashley Trail Suite 019\nSouth Kellychester...,001-689-797-7422x01433
11,134,"83785 Alicia Center\nLake Nathan, AL 76406","6277 Jenkins Cliff Suite 779\nJoelbury, AZ 46805",374-932-7663x9872
12,135,USCGC Jensen\nFPO AP 89636,2974 Gloria Brooks Suite 555\nNew Alexanderche...,(654)459-3789x686
13,136,"32773 Cochran Ford\nSouth Douglas, MD 23775",USS Jones\nFPO AA 74909,+1-977-480-1450x234
14,137,"356 Kirby Shoals\nMillerhaven, IN 33260","1385 Thompson Estates\nPollardmouth, NY 94392",(279)414-5729x3106
15,138,133 Smith Extension Suite 073\nSouth Candacebu...,"672 Fuller Point\nLake Travis, HI 83184",+1-374-774-2448x4834
16,139,"635 Bridget Village Suite 628\nMaloneburgh, CO...",47463 Robinson Ridges Suite 975\nNew Maryborou...,001-537-238-4245x213
17,140,"7465 Lin Freeway Suite 436\nLake Raymond, FL 2...","971 David Burg Suite 563\nNorth Kimshire, MD 1...",506-569-6535x0230
18,141,"6988 Mary Course\nFarmerstad, IL 48478","4116 Mckay Throughway\nSouth Olivia, NE 62732",7958849835
19,142,"0789 Paul Stravenue Apt. 430\nPort Hannahstad,...","6547 Randy Gateway\nNew Anthony, PA 65877",+1-151-249-9750
20,143,"970 Stevens Estate\nAlexanderville, VA 97368","6631 Colleen Port Apt. 526\nDanielleview, WV 4...",(607)638-3303
21,144,"52279 Jones Point\nLake Williamburgh, AZ 32903","83262 Mary Square\nNorth Matthewshire, MT 64097",+1-861-185-0417x4395
22,145,"1249 Angela Valleys\nChristopherstad, CA 18403","34392 Ford Station Apt. 329\nNew Lauren, NC 05539",533-215-8528x06633
23,146,"8124 Burgess Walk Suite 191\nMoodyborough, MI ...",555 David Lodge Suite 397\nNew Patriciachester...,(045)869-0414x7149
24,147,Unit 1656 Box 9488\nDPO AE 93949,"093 Townsend Tunnel Suite 472\nHurstshire, AK ...",+1-486-595-5774x812

In [4]:
# Case 2 - no dataframe

fakeGen = FakeDataGenerator() # no df
fakeGen.add_address('shipping_address')
fakeGen.add_address('billing_address')
fakeGen.add_phone_number('customer_phone')
fakeGen.add_random_number('sale_count', 10, 100)

,shipping_address,billing_address,customer_phone,sale_count
0,"8734 Cooley Land Apt. 554\nSouth Nicholas, IL ...","0070 Ayala Groves\nNorth Wanda, PA 74602",001-396-055-8593x511,19
1,"5623 Michelle Burg\nGarciaview, KS 56232","87170 Brian Bypass Apt. 863\nSouth Betty, FL 3...",001-669-449-0264x2641,85
2,"6418 Abigail Well\nLake Lindaburgh, MI 28923","65920 Sharp Fords Apt. 479\nEllisborough, NH 5...",631-581-8123x223,39
3,"767 Bruce Streets\nSouth Andrea, MO 39031","991 Anna Crescent\nTurnerburgh, ME 61665",+1-124-987-9332x8868,42
4,"1092 Ashley Underpass\nSouth Andreaport, VA 29397",9517 Dickerson Landing Suite 174\nBurgessburgh...,+1-926-021-8339,74